url_shortener/auth.py
import string
from datetime import datetime
from random import choices
from sqlalchemy.orm import validates
from .extensions import db
import logging 


class Admin(db.Model):
    username = db.Column(db.String(5), primary_key=True)
    password = db.Column(db.String(256))
    Attempts = db.Column(db.Integer, default = 0)
    User_Address = db.Column(db.String(128))

url_shortener/docs/scripts/auth.py
import string
from datetime import datetime
from random import choices
from sqlalchemy.orm import validates
from extensions import db
import logging 

""" Creating the Database for the **Admin Panel** """
class Admin(db.Model):
    """ Creating the *admin* table """
    username = db.Column(db.String(5), primary_key=True)
    password = db.Column(db.String(256))
    Attempts = db.Column(db.Integer, default = 0)
    User_Address = db.Column(db.String(128))

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, session,g
import os
from werkzeug.security import generate_password_hash, check_password_hash
import logging
from .extensions import db
from .models import Link
from .auth import Admin
from urllib.parse import urlparse, urljoin
import time

""" All the routes are defined """

short = Blueprint('short', __name__)
@short.route('/<Short_URL>')
def redirect_to_url(Short_URL):
    link = Link.query.filter_by(Short_URL=Short_URL).first_or_404()
    link.Clicks = link.Clicks + 1
    db.session.commit()
    return redirect(link.Original_URL)


@short.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@short.route('/')
def index():
    logging.debug("Service accessed")
    ip =  request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    links = Link.query.order_by(Link.id.desc()).filter_by(User_Address  = ip)
    return render_template('home.html', links = links)

@short.route('/lol')
def lol():
    i_got_hashed = generate_password_hash('password','SHA256')
    return i_got_hashed

@short.route('/add_link', methods=['POST'])
def add_link():
    Original_URL = request.form['Original_URL']
    parsed = urlparse(urljoin(Original_URL, '/'))
    # parsed = urlparse(Original_URL)
    check1 = Original_URL.find('www',0,len(Original_URL))
    if check1 == -1:
        checkP = 'N'
    else :
        checkP = 'Y'
    if bool(all([parsed.scheme, parsed.path, parsed.netloc])) != False and ((checkP =='N' and len(parsed.netloc.split(".")) > 1) or (checkP =='Y' and len(parsed.netloc.split(".")) > 2)):
            ip =  request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
            link = Link(Original_URL=Original_URL, User_Address = ip)
            db.session.add(link)
            db.session.commit()
            logging.debug("Link generated successfully!")
            flash("Short URL generated successfully!")
            links = Link.query.order_by(Link.id.desc()).filter_by(User_Address  = ip)
            return render_template('link_added.html', 
                new_link=link.Short_URL, Original_URL=link.Original_URL, links = links)
    else:
        flash("The URL entered is invalid. Please include 'http://' or any other valid scheme.")   
        return redirect(url_for('short.index'))

@short.route('/logs')
# @requires_auth
def stats():
    if g.user:
        links = Link.query.order_by(Link.id.desc()).all()
        ip =  request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
        logging.warning("Database is being accessed by " + ip)
        return render_template('logs.html', links=links)

    return redirect(url_for('short.auth'))


@short.route('/login', methods = ['POST', 'GET'])
def auth():
    session.pop('user',None)
    admin = Admin.query.filter_by(username="admin").first()
    ip =  request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    if request.method == 'POST':
        session.pop('user',None)
        username = request.form['Username']
        password = request.form['Password']
        User = Admin.query.first()
        hashed = check_password_hash(User.password, password)
        if username == User.username and hashed == True:
            admin = Admin.query.filter_by(username="admin").first()
            admin.Attempts = 0
            admin.User_Address = ip
            db.session.commit()
            session['user'] = username
            flash("Login Successful!")
            return redirect(url_for('short.stats'))
        else: 
            admin = Admin.query.filter_by(username="admin").first()
            admin.Attempts = admin.Attempts + 1
            db.session.commit()
            flash("Login Failed.")
            
    return render_template('auth.html')


@short.errorhandler(404)
def page_not_found(e):
    logging.error("Bad Request")
    return render_template('bad.html'), 404

url_shortener/templates/auth.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Authorization
        </title>
        <link rel = "stylesheet" href = "{{url_for('static', filename = 'css/auth.css')}}"
    </head>
    <body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert" role="alert">
        {{message}}
        </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
        <h1>ADMIN PANEL</h1>
        <form action="{{ url_for('short.auth') }}" method = "POST">
        <input type="text" class="Text" name = "Username" placeholder="Username" required/><br /><br />
        <input type="password" class="Text" name = "Password" placeholder="Password" required/><br />
        <input type = "submit" class = "submit" value ="Login" />
        </form>
        <input type = "button" value = "Home"  class = "Home" onclick = "href = location.pathname = '/'"/>
    </body>


</html>

url_shortener/templates/bad.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            404
        </title>
         <link rel = "stylesheet" href = "{{url_for('static', filename = 'css/bad.css')}}"
    </head>
    <body>
        <h1>404 PAGE NOT FOUND</h1>
    </body>


</html>

url_shortener/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Shorten your URL
        </title>
        <link rel = "stylesheet" href = "{{url_for('static', filename = 'css/home.css')}}"
    </head>
    <body>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
                <div class="alert" role="alert">
                {{message}}
                </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            
        <h1>SHORT URL GENERATOR</h1>
        <form action="{{ url_for('short.add_link') }}" method = "POST">
        <input type="text" class="url" name = "Original_URL" placeholder="Enter the URL" required/><br />
        <input type = "submit" value = "Shorten!"  class = "submit"/>
        </form><br /><br />
        {% if links.count() != 0 %}
        <h2>Recent Requests</h2>
        <table cellpadding = "11">
            <tr>
                <th style="width: 45%" class = 'one'>Original URL</th>
                <th style="width: 35%" class = 'two'>Shortened URL</th>
                <th style="width: 20%" class = 'three'>Request Date</th>
            </tr>
            {% if links.count() >= 5 %}
            {% for i in range(5) %}
            <tr>
                <td>{{links[i].Original_URL}}</td>
                <td>{{ url_for('short.redirect_to_url', Short_URL=links[i].Short_URL, _external=True) }}</td>
                <td>{{links[i].Date_Created}}</td>                       
            </tr>
            {% endfor %}
            {% elif links.count() != 0 %}

            {% for i in range(links.count()) %}
            <tr>
                <td>{{links[i].Original_URL}}</td>
                <td>{{ url_for('short.redirect_to_url', Short_URL=links[i].Short_URL, _external=True) }}</a></td>
                <td>{{links[i].Date_Created}}</td>                       
            </tr>
            {% endfor %}
            {% endif %}
            {% endif %}
        </table>
    </body>

</html>

url_shortener/templates/link_added.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Shorten your URL
        </title>
        <link rel = "stylesheet" href = "{{url_for('static', filename = 'css/add.css')}}" />
    </head>
    <body>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
                <div class="alert" role="alert">
                {{message}}
                </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        <h1>SHORT URL GENERATOR</h1>
        <form action="{{ url_for('short.add_link') }}" method = "POST">
        <input type="text" class="url" name = "Original_URL" value = {{Original_URL}}  required/><br />
        <input type = "submit" value = "Shorten!"  class = "submit"/>
        </form><br /><br />
        <h2>Original URL</h2>
        <input type = "text" class = 'url' value = {{Original_URL}} />
        <h2>Shortened URL</h2>
        <input type = "text" class = 'url' value = {{ url_for('short.redirect_to_url', Short_URL=new_link, _external=True) }} /><br />
        <input type = "button" value = "Home"  class = "Logs" onclick = "href = location.pathname = '/'" /><br />
        <input type = "button" value = "Logs"  class = "Home" onclick = "href = location.pathname = '/logs'" />
    </body>

</html>

url_shortener/templates/logs.html
<!DOCTYPE html>
<html>
    <head>
        <title>
           Stats
        </title>
        <link rel = "stylesheet" href = "{{url_for('static', filename = 'css/logs.css')}}"
    </head>
    <body>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
                <div class="alert" style = "color: rgb(23, 168, 23)" role="alert">
                {{message}}
                </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        <h1>LOGS</h1>
        <p><input type = "submit" value = "Logout"  class = "logout" onclick = "href = location.pathname = '/login'" style="float: left; margin-left: 10%" />
        <input type = "submit" value = "Home"  class = "Home" onclick = "href = location.pathname = '/'" style="float: right; margin-right: 8%" /></p><br /><br />
    <table cellpadding = "10">
        <tr>
            <th style="width: 3%" class = 'one'>ID</th>
            <th style="width: 40%">Original URL</th>
            <th style="width: 35%">Shortened URL</th>
            <th style="width: 6%">Clicks</th>
            <th style="width: 16%" class ='last'>Creation Date/Time</th>
        </tr>
        {% for link in links %}
        <tr>
            <td>{{link.id}}</td>
            <td>{{link.Original_URL}}</td>
            <td>{{ url_for('short.redirect_to_url', Short_URL=link.Short_URL, _external=True) }}</td>
            <td>{{link.Clicks}}</td>
            <td>{{link.Date_Created}}</td>
        </tr>
        {% endfor %}
</table>
    </body>

</html>